# Let's test your knowledge about Python, data structures, NumPy, and pandas.
We are going to createa a dummy dataset for some Youtubers regarding their channals. We will create data including:
1.  Decide the size of the dataset by using a SIZE constant variable
1.  ChannelID (`Y0001`, `Y0002`, ...)
1.  Number of subscribers
1.  Number of videos
1.  Number of total views
1.  Category (`['music','news','gaming','food','travel']`)
1.  Language (`['English','Spanish','Japanese','Franch','Russia','Chinese']`)
1.  Type(`['Corperate','Goverment','NGO','Individual']`)


Then we will play with the dummy dataset with our knowledge of pandas, including:
1.  Access
1.  Sampling
1.  Filtering
1.  Aggregation
1.  Manipulation


## Setup environment
Let's import random, Numpy, and pandas

In [1]:
import random
import numpy as np
import pandas as pd

## Dummy dataset generation

### Setup SIZE

In [2]:
# We make this variable SIZE because it supposed to be constant for the runtime.
SIZE = 10000

### Generate ChannelID

In [3]:
ids = ['Y{0:04d}'.format(x) for x in range(SIZE)]
ids[:5], ids[-5:]

(['Y0000', 'Y0001', 'Y0002', 'Y0003', 'Y0004'],
 ['Y9995', 'Y9996', 'Y9997', 'Y9998', 'Y9999'])

### Generate # of subscribers

#### We first simulate a normal distribution

In [4]:
subs = np.random.normal(100000, 50000, (SIZE))
subs[:5], subs[-5:]

(array([ 44482.99124485, 176607.51351968,  60213.09354992,  29833.04722841,
        179785.00272986]),
 array([ 57113.76732009,  64811.90909181,  68363.36933636,  91272.19772383,
        124375.50085848]))

#### We convert the float numbers to integer

In [5]:
subs = subs.astype(int)
subs[:5], subs[-5:]

(array([ 44482, 176607,  60213,  29833, 179785]),
 array([ 57113,  64811,  68363,  91272, 124375]))

#### We check if there are non-positive numbers of subscribers

In [6]:
subs[subs <= 0 ]

array([-63532, -11731,  -3935, -29529, -10874,  -6569, -60675,  -1666,
       -41134, -42947, -19536,  -7582,   -895, -39121, -67012, -15966,
       -36705, -14607, -15630, -10870, -20359, -18448,  -3298,  -5370,
       -44995,  -1788, -10919, -26582, -27456, -22899, -17324,  -1414,
        -7581, -15838,  -9021, -14456,  -2129,  -9550,  -2531,  -5129,
       -35763,  -5905,  -8541, -14836, -24421, -29671, -13253, -30818,
       -13950, -54756,  -3891, -12494,  -2913, -19972,  -8028, -10416,
       -17802,  -6818, -13643, -14343, -28717, -69714, -74120,  -2214,
        -9504,  -3056, -11235, -11880, -14375, -36499, -15238,  -5326,
        -2340,  -6723, -27693,  -9773, -40504, -37201,  -6396, -11128,
        -9811,  -8669, -35447,  -8158,  -8111, -26885,  -2849, -55253,
       -30351, -14518, -10954, -32269, -15231, -20296,  -8777, -19840,
        -3139,  -2601, -13051, -12446,  -9771, -44720, -22156,   -505,
        -5310, -15182, -11006,  -2463,  -4603, -23061,  -9166, -17750,
      

#### We set them to be 1

In [7]:
subs[subs <= 0 ] = 1
subs[subs <= 0 ]

array([], dtype=int32)

### Generate number of videos


#### We use a uniform distribution this time (just for practice)

In [8]:
nvideos = [np.random.randint(1, 100) for i in range(SIZE)]
nvideos[:5], nvideos[-5:]

([96, 8, 23, 96, 82], [21, 39, 27, 51, 6])

### We simulate the number of views

#### To make it real, we will use the # of subscribers and # of videos as factors to get the # of total views

In [9]:
views = [ int(x*1.5*np.random.random() + y*2*np.random.random() + np.random.randint(-1000, 1000))
for x, y in zip(subs, nvideos)]
views[:5], views[-5:]

([49781, 20562, 80857, 35363, 129516], [12450, 93093, 70026, 90704, 37030])

In [10]:
views = np.array(views)
views

array([49781, 20562, 80857, ..., 70026, 90704, 37030])

In [11]:
views[views < 0]

array([-469, -890, -740, -870, -830, -511, -151, -719, -838, -664, -665,
       -314, -826, -351, -555, -359, -841, -791, -580, -204, -103, -955,
       -627, -105, -781, -752,  -85,  -52, -839, -781,  -63, -153, -771,
       -115, -721, -200,  -26, -297,  -75, -865, -593, -168, -349, -522,
       -476, -691, -635, -506, -456, -332, -490, -855, -179, -354, -113,
       -317, -912,  -24, -632, -550, -575, -524, -429, -797, -297,  -93,
       -959, -853, -808, -834, -210, -699, -169, -273,  -65, -501, -393,
       -837, -454, -419, -932, -434, -218, -537, -472, -219, -812,  -30,
       -405, -935, -656, -418, -794, -288, -571, -562, -273, -622, -934,
       -536, -291, -203, -105, -427, -133, -254, -394, -164, -617, -316,
       -470, -410, -223, -368, -778, -345, -839, -452, -200, -803, -161,
       -319, -518, -356, -136, -378, -579, -434, -571, -683, -184, -780,
       -314, -102, -477, -761, -590, -330, -463, -105, -563, -586, -193,
       -661, -821,  -85, -625, -965, -645, -284])

In [12]:
views[views < 0] = 0
views[views < 0]

array([], dtype=int32)

### Category

>Category (`['music','news','gaming','food','travel']`)

In [13]:
category = np.random.choice(['music','news','gaming','food','travel'], SIZE)
category[:20]

array(['news', 'food', 'food', 'travel', 'news', 'music', 'travel',
       'food', 'food', 'music', 'travel', 'gaming', 'music', 'gaming',
       'news', 'gaming', 'news', 'food', 'gaming', 'travel'], dtype='<U6')

### Language
>Language (`['English','Spanish','Japanese','Franch','Russia','Chinese']`)


In [14]:
language = np.random.choice(['English','Spanish','Japanese','Franch','Russia','Chinese'],
                            SIZE, p=[0.5, 0.1, 0.1, 0.1, 0.1, 0.1])
language[:20]

array(['English', 'English', 'English', 'English', 'English', 'English',
       'Chinese', 'Japanese', 'Chinese', 'English', 'English', 'Chinese',
       'Japanese', 'Spanish', 'English', 'Franch', 'Spanish', 'Chinese',
       'Russia', 'English'], dtype='<U8')

### Type
>Type(`['Corperate','Goverment','NGO','Individual']`)

In [15]:
tp = np.random.choice(['Corperate','Goverment','NGO','Individual'], SIZE, p=[0.1, 0.2, 0.3, 0.4])
tp[:20]

array(['NGO', 'Individual', 'Individual', 'Corperate', 'Goverment', 'NGO',
       'Individual', 'NGO', 'Individual', 'NGO', 'Goverment', 'Goverment',
       'Goverment', 'Individual', 'NGO', 'NGO', 'Individual', 'NGO',
       'Individual', 'Individual'], dtype='<U10')

### Now we have all attributes, let's put them into a dataframe

In [16]:
df = pd.DataFrame({'ChannelID': ids,
                   'subs': subs,
                   'nvideos': nvideos,
                   'views': views,
                   'Category': category,
                   'Language':language,
                   'Type': tp},
                  index = ids)
df.head()

ChannelID    subs  nvideos   views Category Language        Type
Y0000     Y0000   44482       96   49781     news  English         NGO
Y0001     Y0001  176607        8   20562     food  English  Individual
Y0002     Y0002   60213       23   80857     food  English  Individual
Y0003     Y0003   29833       96   35363   travel  English   Corperate
Y0004     Y0004  179785       82  129516     news  English   Goverment

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, Y0000 to Y9999
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ChannelID  10000 non-null  object
 1   subs       10000 non-null  int32 
 2   nvideos    10000 non-null  int64 
 3   views      10000 non-null  int32 
 4   Category   10000 non-null  object
 5   Language   10000 non-null  object
 6   Type       10000 non-null  object
dtypes: int32(2), int64(1), object(4)
memory usage: 546.9+ KB


### Let's save the dummy dataset to `youtube_channels.csv`

In [18]:
df.to_csv('/content/youtube_channels.csv', index=False)

OSError: Cannot save file into a non-existent directory: '\content'

## Let's play with the dataframe a little bit

### Sampling

#### Select certain rows

In [20]:
df_sub1 = df.loc[:'Y0100']
df_sub1

ChannelID    subs  nvideos   views Category  Language        Type
Y0000     Y0000   44482       96   49781     news   English         NGO
Y0001     Y0001  176607        8   20562     food   English  Individual
Y0002     Y0002   60213       23   80857     food   English  Individual
Y0003     Y0003   29833       96   35363   travel   English   Corperate
Y0004     Y0004  179785       82  129516     news   English   Goverment
...         ...     ...      ...     ...      ...       ...         ...
Y0096     Y0096   41962       56   39568     news    Franch  Individual
Y0097     Y0097  123369       11    4216    music   English         NGO
Y0098     Y0098       1       45       0   travel  Japanese   Goverment
Y0099     Y0099   21819       94   17564   gaming   Chinese         NGO
Y0100     Y0100       1       52       0     news   English  Individual

[101 rows x 7 columns]

#### Select certain rows and columns

In [21]:
df_sub2 = df.loc[:'Y1000', ['subs','views']]
df_sub2

subs   views
Y0000   44482   49781
Y0001  176607   20562
Y0002   60213   80857
Y0003   29833   35363
Y0004  179785  129516
...       ...     ...
Y0996   83520   12945
Y0997  134914  195496
Y0998   96432   34570
Y0999  200406  227134
Y1000  182608  191332

[1001 rows x 2 columns]

#### Select randome rows

In [22]:
df_sub3 = df.iloc[random.sample(range(0, SIZE), 100)]
df_sub3

ChannelID    subs  nvideos   views Category  Language        Type
Y4226     Y4226   92046       30   90104     news   Spanish  Individual
Y2311     Y2311   30485       24    5860   travel   English  Individual
Y9384     Y9384   92539        8   22667   travel   English   Corperate
Y3464     Y3464  146041       38   62707   travel   Spanish         NGO
Y9019     Y9019   27763       52   30874   travel   English  Individual
...         ...     ...      ...     ...      ...       ...         ...
Y1688     Y1688  143387       89  207832   travel   Chinese   Goverment
Y6823     Y6823  125830       50   88417   gaming   Spanish  Individual
Y5571     Y5571  125580       72  120072    music   English         NGO
Y9581     Y9581   74680       71   46385    music   English  Individual
Y5592     Y5592  108162       10    9597     food  Japanese         NGO

[100 rows x 7 columns]

#### Select random rows with selected columns

In [23]:
df_sub4 = df.iloc[random.sample(range(0, SIZE), 100)][['subs','views']]
df_sub4

subs   views
Y9982  187151  267597
Y9805   42036   10288
Y5208    6147    7201
Y4411   95666   99847
Y9766   39217   38887
...       ...     ...
Y3046  166390  160306
Y2453  101318   40493
Y8508  148543   32646
Y1518    6458    2166
Y0343  107101  151311

[100 rows x 2 columns]

### Filtering

#### Super Popular Channel

In [24]:
df_superp = df[df['subs'] > 300000]
df_superp

ChannelID    subs  nvideos   views Category Language       Type
Y0643     Y0643  321873       88  242709     food  English        NGO
Y3034     Y3034  303691       71    6189   gaming  Chinese  Goverment

#### Popular Channel

In [25]:
df_p = df[df['subs'] > 100000]
df_p

ChannelID    subs  nvideos   views Category  Language        Type
Y0001     Y0001  176607        8   20562     food   English  Individual
Y0004     Y0004  179785       82  129516     news   English   Goverment
Y0005     Y0005  146666       55   40357    music   English         NGO
Y0006     Y0006  190942       56  148406   travel   Chinese  Individual
Y0007     Y0007  134727        1   81108     food  Japanese         NGO
...         ...     ...      ...     ...      ...       ...         ...
Y9988     Y9988  134029        5  159874   travel  Japanese   Goverment
Y9991     Y9991  102362       10   33435   travel   English         NGO
Y9993     Y9993  114857        8   78133   gaming   English   Goverment
Y9994     Y9994  113905       71    9627   travel    Franch  Individual
Y9999     Y9999  124375        6   37030     food   English  Individual

[4959 rows x 7 columns]

#### Start up channel

In [26]:
df_begin = df[df['subs'] < 100]
df_begin

ChannelID  subs  nvideos  views Category  Language        Type
Y0032     Y0032     1        1      0     news   English  Individual
Y0065     Y0065     1       61      0   gaming   Spanish         NGO
Y0076     Y0076     1       93    205   gaming   English         NGO
Y0092     Y0092     1       49      0     food   Spanish  Individual
Y0098     Y0098     1       45      0   travel  Japanese   Goverment
...         ...   ...      ...    ...      ...       ...         ...
Y9776     Y9776     1       65    192     news   English   Goverment
Y9789     Y9789     1       98      0   gaming    Russia         NGO
Y9811     Y9811     1       33      0   travel   English  Individual
Y9856     Y9856     1        7      0    music   English   Goverment
Y9987     Y9987     1       21      0     food   English         NGO

[232 rows x 7 columns]

#### Popular English Channel

In [27]:
df_EnglishP = df[(df['subs'] > 100000) & (df['Language'] == 'English')]
df_EnglishP

ChannelID    subs  nvideos   views Category Language        Type
Y0001     Y0001  176607        8   20562     food  English  Individual
Y0004     Y0004  179785       82  129516     news  English   Goverment
Y0005     Y0005  146666       55   40357    music  English         NGO
Y0009     Y0009  156943       14  160076    music  English         NGO
Y0010     Y0010  131931       25  143042   travel  English   Goverment
...         ...     ...      ...     ...      ...      ...         ...
Y9978     Y9978  168389       63  150843     food  English  Individual
Y9984     Y9984  143822        8  172928   gaming  English   Corperate
Y9991     Y9991  102362       10   33435   travel  English         NGO
Y9993     Y9993  114857        8   78133   gaming  English   Goverment
Y9999     Y9999  124375        6   37030     food  English  Individual

[2409 rows x 7 columns]

#### Gaming channel with many videos

In [28]:
df_gaming_nv = df[(df['Category'] == 'gaming') & (df['nvideos'] > 90)]
df_gaming_nv

ChannelID    subs  nvideos   views Category  Language        Type
Y0076     Y0076       1       93     205   gaming   English         NGO
Y0099     Y0099   21819       94   17564   gaming   Chinese         NGO
Y0187     Y0187  129228       91  109597   gaming  Japanese  Individual
Y0206     Y0206  198932       97  212016   gaming   English  Individual
Y0264     Y0264   57831       94   67370   gaming   English   Goverment
...         ...     ...      ...     ...      ...       ...         ...
Y9925     Y9925   68215       97   56133   gaming   Spanish  Individual
Y9931     Y9931   70276       92   10951   gaming   English         NGO
Y9934     Y9934   90680       99   20273   gaming   English   Corperate
Y9975     Y9975   50947       98   55578   gaming   English         NGO
Y9976     Y9976   97829       92  106162   gaming  Japanese  Individual

[180 rows x 7 columns]

#### Non-Corperate and News channel

In [29]:
df_nc_news = df[(df['Category'] == 'news') & (df['Type'] != 'Corperate')]
df_nc_news

ChannelID    subs  nvideos   views Category Language        Type
Y0000     Y0000   44482       96   49781     news  English         NGO
Y0004     Y0004  179785       82  129516     news  English   Goverment
Y0014     Y0014   62475       74   66327     news  English         NGO
Y0016     Y0016  161597       91   42770     news  Spanish  Individual
Y0021     Y0021   51543       93   48154     news  English         NGO
...         ...     ...      ...     ...      ...      ...         ...
Y9963     Y9963  135758       37  168843     news  English  Individual
Y9964     Y9964  179037       39    2640     news  English   Goverment
Y9965     Y9965  114279       27  156007     news   Russia  Individual
Y9970     Y9970  157569       68  175916     news  English   Goverment
Y9992     Y9992   98536       56   78553     news  Spanish  Individual

[1794 rows x 7 columns]

#### Top Subs **and** Top nvideos

In [30]:
df_subs_and_nvideos = df[(df['subs'] > 200000) & (df['nvideos'] > 90)]
df_subs_and_nvideos

ChannelID    subs  nvideos   views Category  Language        Type
Y0055     Y0055  207662       99  288004     food   English  Individual
Y0659     Y0659  213050       95  295093   gaming   English         NGO
Y1877     Y1877  208219       97  306345     news  Japanese         NGO
Y3612     Y3612  253520       98   26260   gaming   English         NGO
Y4297     Y4297  223728       93  268841   travel  Japanese         NGO
Y4568     Y4568  225687       99  280348    music   Chinese  Individual
Y5261     Y5261  208965       93  257689   travel   English  Individual
Y5262     Y5262  211078       93  269259   travel  Japanese  Individual
Y6197     Y6197  205754       94  183966   travel   English  Individual
Y6474     Y6474  234659       94  299274    music   Chinese         NGO
Y7229     Y7229  205527       97  207630     food   Chinese   Goverment
Y7323     Y7323  209274       93  297734   gaming  Japanese  Individual
Y7750     Y7750  201605       99  195805    music  Japanese  Individual
Y8027     Y8027  220973       91  172809   travel    Russia  Individual
Y8638     Y8638  203866       99  162082    music   Chinese  Individual
Y9076     Y9076  200980       96  156056   travel    Franch   Goverment
Y9380     Y9380  215150       91  203610   gaming    Russia   Goverment
Y9407     Y9407  202657       96  193601   gaming   English  Individual

#### Top Subs **or** Top nvideos

In [31]:
df_subs_or_nvideos = df[(df['subs'] > 200000) | (df['nvideos'] > 90)]
df_subs_or_nvideos

ChannelID    subs  nvideos   views Category  Language        Type
Y0000     Y0000   44482       96   49781     news   English         NGO
Y0003     Y0003   29833       96   35363   travel   English   Corperate
Y0012     Y0012  109009       94   25198    music  Japanese   Goverment
Y0016     Y0016  161597       91   42770     news   Spanish  Individual
Y0019     Y0019  158350       92   61522   travel   English  Individual
...         ...     ...      ...     ...      ...       ...         ...
Y9944     Y9944   43271       96    1767     food   English  Individual
Y9946     Y9946  121348       96   52630     food   English         NGO
Y9975     Y9975   50947       98   55578   gaming   English         NGO
Y9976     Y9976   97829       92  106162   gaming  Japanese  Individual
Y9979     Y9979  230565       79  155512   travel    Russia         NGO

[1053 rows x 7 columns]

### Aggregation

In [32]:
byCategory = df.groupby('Category')
byCategory.sum()

ChannelID       subs  \
Category                                                                 
food      Y0001Y0002Y0007Y0008Y0017Y0020Y0022Y0027Y0029Y...  191529993   
gaming    Y0011Y0013Y0015Y0018Y0026Y0033Y0039Y0047Y0065Y...  200541478   
music     Y0005Y0009Y0012Y0023Y0028Y0040Y0046Y0057Y0061Y...  201868357   
news      Y0000Y0004Y0014Y0016Y0021Y0032Y0041Y0044Y0048Y...  200211453   
travel    Y0003Y0006Y0010Y0019Y0024Y0025Y0030Y0031Y0036Y...  200424304   

          nvideos      views  \
Category                       
food        96968  140597459   
gaming      99734  149642004   
music      101352  151950102   
news        98621  152132556   
travel     102512  153500745   

                                                   Language  \
Category                                                      
food      EnglishEnglishJapaneseChineseChineseEnglishSpa...   
gaming    ChineseSpanishFranchRussiaEnglishFranchFranchE...   
music     EnglishEnglishJapaneseEnglishEnglishEnglishSpa...   
news      EnglishEnglishEnglishSpanishEnglishEnglishJapa...   
travel    EnglishChineseEnglishEnglishJapaneseEnglishEng...   

                                                       Type  
Category                                                     
food      IndividualIndividualNGOIndividualNGONGOGoverme...  
gaming    GovermentIndividualNGOIndividualNGOCorperateGo...  
music     NGONGOGovermentIndividualIndividualIndividualG...  
news      NGOGovermentNGOIndividualNGOIndividualNGOIndiv...  
travel    CorperateIndividualGovermentIndividualGovermen...

In [33]:
byCategory.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
byLanguage = df.groupby('Language')
byLanguage.sum()

In [34]:
byLanguage.mean()

NameError: name 'byLanguage' is not defined

In [35]:
byLanType = df.groupby(['Language', 'Type'])
byLanType.describe()

subs                                              \
                      count           mean           std  min       25%   
Language Type                                                             
Chinese  Corperate     95.0   97908.915789  52232.598906  1.0  56598.00   
         Goverment    200.0  101341.930000  49177.681068  1.0  65079.75   
         Individual   396.0  101160.775253  49314.144395  1.0  65382.50   
         NGO          284.0   99606.288732  48317.776757  1.0  64048.25   
English  Corperate    508.0  102535.031496  47384.878332  1.0  71560.00   
         Goverment    947.0  100035.797254  48937.303790  1.0  64964.50   
         Individual  1965.0   98153.867176  48581.800559  1.0  65971.00   
         NGO         1531.0   96605.658393  50045.514063  1.0  61627.50   
Franch   Corperate     92.0  102003.739130  52721.087118  1.0  64598.50   
         Goverment    201.0  102048.004975  50088.119357  1.0  69357.00   
         Individual   410.0  102912.585366  47015.841064  1.0  65746.25   
         NGO          308.0   96799.779221  46669.528090  1.0  63153.75   
Japanese Corperate    103.0   96747.466019  47821.154583  1.0  61957.50   
         Goverment    212.0  101255.783019  49638.202536  1.0  65857.25   
         Individual   429.0   99217.363636  49281.677387  1.0  64637.00   
         NGO          321.0  100726.554517  49509.685707  1.0  68363.00   
Russia   Corperate    105.0  101801.638095  50992.290460  1.0  63334.00   
         Goverment    199.0  100084.040201  49817.588359  1.0  69109.50   
         Individual   415.0  103500.400000  48331.819493  1.0  69807.00   
         NGO          291.0   99502.302405  46138.058219  1.0  68988.50   
Spanish  Corperate    100.0   99242.830000  51287.383498  1.0  62378.25   
         Goverment    181.0  105518.508287  50292.451440  1.0  67173.00   
         Individual   392.0   98197.433673  46923.958766  1.0  65695.75   
         NGO          315.0   97769.076190  49954.052055  1.0  63823.50   

                                                   nvideos             ...  \
                          50%        75%       max   count       mean  ...   
Language Type                                                          ...   
Chinese  Corperate    98377.0  132183.00  210718.0    95.0  47.578947  ...   
         Goverment   104595.5  130334.50  303691.0   200.0  49.800000  ...   
         Individual   99733.0  136025.25  225687.0   396.0  50.737374  ...   
         NGO          96793.5  133525.00  244896.0   284.0  50.517606  ...   
English  Corperate   103832.5  138628.50  256553.0   508.0  49.769685  ...   
         Goverment    99858.0  133713.50  255885.0   947.0  50.876452  ...   
         Individual   98036.0  130703.00  246683.0  1965.0  50.706361  ...   
         NGO          95415.0  128814.00  321873.0  1531.0  49.702809  ...   
Franch   Corperate   104966.5  137743.75  280564.0    92.0  49.413043  ...   
         Goverment   106412.0  132162.00  244307.0   201.0  48.835821  ...   
         Individual  104738.0  140089.75  235334.0   410.0  50.782927  ...   
         NGO          95671.5  133027.50  218805.0   308.0  51.503247  ...   
Japanese Corperate    93838.0  130793.50  221648.0   103.0  49.601942  ...   
         Goverment   102089.0  135401.75  239551.0   212.0  49.084906  ...   
         Individual   99976.0  130893.00  218295.0   429.0  48.862471  ...   
         NGO         101226.0  135166.00  237313.0   321.0  48.255452  ...   
Russia   Corperate    95943.0  137984.00  249964.0   105.0  47.323810  ...   
         Goverment   100115.0  134548.50  233749.0   199.0  50.371859  ...   
         Individual  103706.0  135012.50  294045.0   415.0  49.144578  ...   
         NGO          99934.0  129567.00  242085.0   291.0  50.611684  ...   
Spanish  Corperate    98619.5  138514.25  213429.0   100.0  51.290000  ...   
         Goverment   108997.0  144832.00  235400.0   181.0  48.127072  ...   
         Individual   99468.5  132011.50  22130

In [36]:
byLanType.describe()[['subs','views']]

subs                                              \
                      count           mean           std  min       25%   
Language Type                                                             
Chinese  Corperate     95.0   97908.915789  52232.598906  1.0  56598.00   
         Goverment    200.0  101341.930000  49177.681068  1.0  65079.75   
         Individual   396.0  101160.775253  49314.144395  1.0  65382.50   
         NGO          284.0   99606.288732  48317.776757  1.0  64048.25   
English  Corperate    508.0  102535.031496  47384.878332  1.0  71560.00   
         Goverment    947.0  100035.797254  48937.303790  1.0  64964.50   
         Individual  1965.0   98153.867176  48581.800559  1.0  65971.00   
         NGO         1531.0   96605.658393  50045.514063  1.0  61627.50   
Franch   Corperate     92.0  102003.739130  52721.087118  1.0  64598.50   
         Goverment    201.0  102048.004975  50088.119357  1.0  69357.00   
         Individual   410.0  102912.585366  47015.841064  1.0  65746.25   
         NGO          308.0   96799.779221  46669.528090  1.0  63153.75   
Japanese Corperate    103.0   96747.466019  47821.154583  1.0  61957.50   
         Goverment    212.0  101255.783019  49638.202536  1.0  65857.25   
         Individual   429.0   99217.363636  49281.677387  1.0  64637.00   
         NGO          321.0  100726.554517  49509.685707  1.0  68363.00   
Russia   Corperate    105.0  101801.638095  50992.290460  1.0  63334.00   
         Goverment    199.0  100084.040201  49817.588359  1.0  69109.50   
         Individual   415.0  103500.400000  48331.819493  1.0  69807.00   
         NGO          291.0   99502.302405  46138.058219  1.0  68988.50   
Spanish  Corperate    100.0   99242.830000  51287.383498  1.0  62378.25   
         Goverment    181.0  105518.508287  50292.451440  1.0  67173.00   
         Individual   392.0   98197.433673  46923.958766  1.0  65695.75   
         NGO          315.0   97769.076190  49954.052055  1.0  63823.50   

                                                     views                \
                          50%        75%       max   count          mean   
Language Type                                                              
Chinese  Corperate    98377.0  132183.00  210718.0    95.0  72980.926316   
         Goverment   104595.5  130334.50  303691.0   200.0  74512.845000   
         Individual   99733.0  136025.25  225687.0   396.0  73535.151515   
         NGO          96793.5  133525.00  244896.0   284.0  75312.623239   
English  Corperate   103832.5  138628.50  256553.0   508.0  76032.206693   
         Goverment    99858.0  133713.50  255885.0   947.0  76409.967265   
         Individual   98036.0  130703.00  246683.0  1965.0  74048.466158   
         NGO          95415.0  128814.00  321873.0  1531.0  71845.375572   
Franch   Corperate   104966.5  137743.75  280564.0    92.0  78640.000000   
         Goverment   106412.0  132162.00  244307.0   201.0  79112.915423   
         Individual  104738.0  140089.75  235334.0   410.0  78063.678049   
         NGO          95671.5  133027.50  218805.0   308.0  70601.152597   
Japanese Corperate    93838.0  130793.50  221648.0   103.0  78792.621359   
         Goverment   102089.0  135401.75  239551.0   212.0  74684.410377   
         Individual   99976.0  130893.00  218295.0   429.0  74075.123543   
         NGO         101226.0  135166.00  237313.0   321.0  73165.538941   
Russia   Corperate    95943.0  137984.00  249964.0   105.0  77213.590476   
         Goverment   100115.0  134548.50  233749.0   199.0  80881.869347   
         Individual  103706.0  135012.50  294045.0   415.0  77613.404819   
         NGO          99934.0  129567.00  242085.0   291.0  75101.233677   
Spanish  Corperate    98619.5  138514.25  213429.0   100.0  73432.170000   
         Goverment   108997.0  144832.00  235400.0   181.0  82032.364641   
         Individual   99468.5  132011.50  221303.0   392.0  73392.403061   
         NGO         

In [37]:
byLanType.describe().loc['English',['subs','views']]

subs                                                       \
             count           mean           std  min      25%       50%   
Type                                                                      
Corperate    508.0  102535.031496  47384.878332  1.0  71560.0  103832.5   
Goverment    947.0  100035.797254  48937.303790  1.0  64964.5   99858.0   
Individual  1965.0   98153.867176  48581.800559  1.0  65971.0   98036.0   
NGO         1531.0   96605.658393  50045.514063  1.0  61627.5   95415.0   

                                 views                                   \
                 75%       max   count          mean           std  min   
Type                                                                      
Corperate   138628.5  256553.0   508.0  76032.206693  62317.548283  0.0   
Goverment   133713.5  255885.0   947.0  76409.967265  61848.897923  0.0   
Individual  130703.0  246683.0  1965.0  74048.466158  61138.054009  0.0   
NGO         128814.0  321873.0  1531.0  71845.375572  60364.714458  0.0   

                                                   
                25%      50%        75%       max  
Type                                               
Corperate   21791.5  63178.0  112693.75  303296.0  
Goverment   24937.5  63423.0  115745.50  289993.0  
Individual  23146.0  60205.0  113760.00  298941.0  
NGO         22488.5  58561.0  105547.50  349376.0

### Manipulation

In [38]:
df['subpervideo'] = df['subs']/df['nvideos']
df['subpervideo'].describe()

count     10000.000000
mean       5336.611922
std       13720.900397
min           0.010101
25%        1167.809659
50%        1978.432359
75%        3902.000000
max      208475.000000
Name: subpervideo, dtype: float64

In [39]:
df['viewspervideo'] = df['views']/df['nvideos']
df['viewspervideo'].describe()

count     10000.000000
mean       4022.532047
std       12117.933654
min           0.000000
25%         517.392324
50%        1338.933036
75%        2903.067620
max      255420.000000
Name: viewspervideo, dtype: float64

In [40]:
df['viewspersub'] = df['views']/df['subs']
df['viewspersub'].describe()

count    10000.000000
mean         6.408630
std         62.205288
min          0.000000
25%          0.364387
50%          0.752118
75%          1.135747
max       1074.000000
Name: viewspersub, dtype: float64

In [41]:
df.head(10)

ChannelID    subs  nvideos   views Category  Language        Type  \
Y0000     Y0000   44482       96   49781     news   English         NGO   
Y0001     Y0001  176607        8   20562     food   English  Individual   
Y0002     Y0002   60213       23   80857     food   English  Individual   
Y0003     Y0003   29833       96   35363   travel   English   Corperate   
Y0004     Y0004  179785       82  129516     news   English   Goverment   
Y0005     Y0005  146666       55   40357    music   English         NGO   
Y0006     Y0006  190942       56  148406   travel   Chinese  Individual   
Y0007     Y0007  134727        1   81108     food  Japanese         NGO   
Y0008     Y0008   66578       71    2798     food   Chinese  Individual   
Y0009     Y0009  156943       14  160076    music   English         NGO   

         subpervideo  viewspervideo  viewspersub  
Y0000     463.354167     518.552083     1.119127  
Y0001   22075.875000    2570.250000     0.116428  
Y0002    2617.956522    3515.521739     1.342850  
Y0003     310.760417     368.364583     1.185365  
Y0004    2192.500000    1579.463415     0.720394  
Y0005    2666.654545     733.763636     0.275163  
Y0006    3409.678571    2650.107143     0.777231  
Y0007  134727.000000   81108.000000     0.602017  
Y0008     937.718310      39.408451     0.042026  
Y0009   11210.214286   11434.000000     1.019963

## Congratulations! You completed our course: Data Wrangling -- Fundamentals