# Numpy!

This section is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. Most codes are hidden and you can only see the output.

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [1]:
# your code is here
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [4]:
# your code is here
lista = [1,2,3,4,5,6,7,8,9,0]
np_array = np.array(lista)

print(np_array)

[1 2 3 4 5 6 7 8 9 0]


### Task: Create a numpy array of size 6, filled with zeros

In [6]:
# your code is here
zero = np.zeros(6)
print(zero)

[0. 0. 0. 0. 0. 0.]


### Task: Create a numpy array of size 6, filled with ones

In [7]:
# your code is here
one = np.ones(6)
print(one)

[1. 1. 1. 1. 1. 1.]


### Task: Create a numpy array with values from 0 to 10

In [9]:
# your code is here
zero_to_ten = np.arange(0,11)
print(zero_to_ten)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [11]:
# your code is here
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


### Task: Create a numpy matrix of 3*2 integers, filled with ones

In [12]:
# your code is here
one = np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [13]:
# your code is here
rand_matrix = np.random.randint(0,10,(3,2))
print(rand_matrix)

[[8 0]
 [1 6]
 [8 6]]


### Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [15]:
# your code is here
rand_matrix = np.random.random((100,2))
print(rand_matrix)

[[0.21049802 0.58640275]
 [0.83100221 0.9109853 ]
 [0.51476044 0.05624128]
 [0.09142598 0.16911188]
 [0.76373307 0.09284086]
 [0.94582411 0.33120387]
 [0.14315497 0.43888425]
 [0.9947242  0.3231933 ]
 [0.56367516 0.38002768]
 [0.0945218  0.35086376]
 [0.12969761 0.21309446]
 [0.41445325 0.12992995]
 [0.13773493 0.50689164]
 [0.85709516 0.81010887]
 [0.17081328 0.94274757]
 [0.07464207 0.36398984]
 [0.01967158 0.25685437]
 [0.19016854 0.82705581]
 [0.83197279 0.48317247]
 [0.1165068  0.72871067]
 [0.39788129 0.18659163]
 [0.05109269 0.55964214]
 [0.49032129 0.91846467]
 [0.41871669 0.94444934]
 [0.89446303 0.63312049]
 [0.12677155 0.78549363]
 [0.89941678 0.87426947]
 [0.58231991 0.74122397]
 [0.09987094 0.5499998 ]
 [0.00246075 0.88829884]
 [0.33057518 0.54957537]
 [0.26797626 0.34804397]
 [0.12390263 0.7190601 ]
 [0.97414899 0.69250497]
 [0.11496703 0.08410296]
 [0.92162864 0.85979869]
 [0.84811567 0.15121334]
 [0.78886364 0.57452251]
 [0.54109967 0.87258418]
 [0.74365265 0.16578252]


### Task: Create a numpy matrix of 2\*3\*4, filled with integers from 1 to 24.

In [17]:
# your code is here
rand_matrix = np.random.randint(1,24,(2,3,4))
print(rand_matrix)

[[[17 10 11  1]
  [20 17  6  8]
  [16 13 10  9]]

 [[23 12 11  7]
  [ 3  3  8 21]
  [11 22  6  8]]]


## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [52]:
# your code is here
X = np.array([1, 2, 3, 4, 5])

### Task: Show the first element of X

In [53]:
# your code is here
print(X[0])

1


### Task: Show the last element of X

In [54]:
# your code is here
print(X[-1])

5


### Task: Show the first 3 elements of X

In [55]:
# your code is here
print(X[:3])

[1 2 3]


### Task: Show the last 3 elements of X

In [56]:
# your code is here
print(X[-2:])

[4 5]


### Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [57]:
# your code is here
print(X[::2])

[1 3 5]


### Task: Show the elements of X except the last one

In [58]:
# your code is here
print(X[:-1])

[1 2 3 4]


### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [59]:
# your code is here
X = np.arange(12).reshape((3,4))
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Task: Show the first row of X

In [60]:
# your code is here
print(X[0])

[0 1 2 3]


### Task: Show the first column of X

In [61]:
# your code is here
print(X[:,0])

[0 4 8]


### Task: Show the first element of the first row of X

In [62]:
# your code is here
print(X[0,0])

0


### Task: Show the last row of X

In [63]:
# your code is here
print(X[-1])

[ 8  9 10 11]


### Task: Show the last column of X

In [64]:
# your code is here
print(X[:,-1])

[ 3  7 11]


### Task: Show the last element of the last row of X

In [65]:
# your code is here
print(X[-1,-1])

11


### Task: Show all the rows except the last row of X

In [66]:
# your code is here
print(X[:-1])

[[0 1 2 3]
 [4 5 6 7]]


### Task: Show all the columns except the last column of X

In [67]:
# your code is here
print(X[:,:-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


### Task: Show the first two elements of the first two rows

In [68]:
# your code is here
print(X[:2,:2])

[[0 1]
 [4 5]]


## Array Statistics

### Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [74]:
# your code is here
print(X.sum(), X.mean(), X.std(), X.var(), X.min(), X.max())

66 5.5 3.452052529534663 11.916666666666666 0 11


### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [75]:
# your code is here
X1 = X[0]
print(X1.sum(), X1.mean(), X1.std(), X1.var(), X1.min(), X1.max())

6 1.5 1.118033988749895 1.25 0 3


### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [76]:
# your code is here
X2 = X[:,0]
print(X2.sum(), X2.mean(), X2.std(), X2.var(), X2.min(), X2.max())

12 4.0 3.265986323710904 10.666666666666666 0 8


## Array Linear Algebra

### Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc.

In [84]:
# your code is here
A = np.random.randint(0,100,(2,2))
B = np.random.randint(0,100,(2,2))

print(A + B, A - B, A * B, np.dot(A,B))

[[ 60 116]
 [ 77 111]] [[44 66]
 [11 39]] [[ 416 2275]
 [1452 2700]] [[3419 4576]
 [2827 3800]]
