# Multi-dimensional arrays

## Creation and properties

In [2]:
import numpy as np

In [5]:
mda = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [9]:
print('Number of dimensions: ',mda.ndim)
print('Second row: ',mda[1])
print('Second column: ',mda[:,1])
print('Second element in second row: ',mda[1,1])

Number of dimensions:  2
Second row:  [4 5 6]
Second column:  [2 5 8]
Second element in second row:  5


In [11]:
print(np.size(mda))

9


In [12]:
print(np.size(mda, 1))

3


In [13]:
print(mda.shape)

(3, 3)


## Access

### Retrieve row

In [15]:
row2 = mda[1]
print(row2, type(row2),row2.ndim)

[4 5 6] <class 'numpy.ndarray'> 1


### Retrieve cell within row

In [16]:
row3 = mda[2]
row3cell2 = row3[1]
print(row3cell2)

8


In [17]:
row3cell2 = mda[2,1]
print(row3cell2)

8


### Retrieve all rows

In [18]:
all_rows = mda[0:len(mda)]
print(all_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
all_rows = mda[:]
print(all_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Retrieve one column

In [20]:
col2 = mda[:,1]
print(col2)

[2 5 8]


### Retrieve last two columns

In [21]:
cols2and3 = mda[:,1:]
print(cols2and3)

[[2 3]
 [5 6]
 [8 9]]


In [23]:
cols2and3 = mda[:,-2:]
print(cols2and3)

[[2 3]
 [5 6]
 [8 9]]


## Manipulation

### Add '2' to the last two elements of the last two rows

In [26]:
print(mda)
print('-' * 9)
mda[-2:,-2:] += 2
print(mda)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------
[[ 1  2  3]
 [ 4  7  8]
 [ 7 10 11]]


### Add a row vector to all rows

In [29]:
mda = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
v = [10,20,30]
print(mda + v)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Different ways to create arrays

In [32]:
ar1 = np.zeros(shape=(6,3), dtype=float)
print(ar1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
ar2 = np.reshape(ar1, (2,-1))
print(ar2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
ar3 = np.reshape(ar1, (-1,2))
print(ar3)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [36]:
ar4 = np.linspace(4,6,5)
print(ar4)

[4.  4.5 5.  5.5 6. ]


In [38]:
ar5 = np.arange(1,7).reshape(2,3)
ar6 = np.arange(7,13).reshape(2,3)
print(ar5)
print(ar6)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [39]:
print(ar5 + ar6)

[[ 8 10 12]
 [14 16 18]]


In [40]:
print(ar5 * ar6)

[[ 7 16 27]
 [40 55 72]]


In [41]:
print(ar5.T)

[[1 4]
 [2 5]
 [3 6]]


In [42]:
print(ar5.T@ar6)

[[47 52 57]
 [64 71 78]
 [81 90 99]]


In [43]:
print(ar5.T.dot(ar6))

[[47 52 57]
 [64 71 78]
 [81 90 99]]


In [44]:
print(ar6@ar5.T)

[[ 50 122]
 [ 68 167]]
