## Basics

In [1]:
import numpy as np

In [4]:
[x ** 2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [5]:
np.arange(10) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Efficiency

In [26]:
%timeit -n 1000 [x ** 2 for x in range(10)]
%timeit -n 1000 np.arange(10) ** 2

771 ns ± 117 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
1.49 µs ± 509 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Creation

In [2]:
ls = [1,2,3,4,5]
np.array(ls)

array([1, 2, 3, 4, 5])

In [9]:
ar1 = np.arange(10)
print('ar1:',ar1)

ar2 = np.arange(5,11)
print('ar2:',ar2)

ar3 = np.arange(0,13,3)
print('ar3:',ar3)

ar4 = np.arange(4,-4,-1)
print('ar4:',ar4)

ar1: [0 1 2 3 4 5 6 7 8 9]
ar2: [ 5  6  7  8  9 10]
ar3: [ 0  3  6  9 12]
ar4: [ 4  3  2  1  0 -1 -2 -3]


In [12]:
ar5 = np.arange(1,5,1)
print('ar5:',ar5,type(ar5[0]))

ar6 = np.arange(1,5,0.5)
print('ar6',ar6,type(ar6[0]))

ar7 = np.arange(1,5,dtype=float)
print('ar7:',ar7,type(ar7[0]))

ar5: [1 2 3 4] <class 'numpy.int32'>
ar6 [1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.float64'>
ar7: [1. 2. 3. 4.] <class 'numpy.float64'>


## Getting basic information about and array

In [17]:
ar = np.array([1,2,3,4,5])
array_type = type(ar)
array_size = np.size(ar)
array_dimensions = ar.ndim
array_data_type = ar.dtype

print(f'''Object type: {array_type},
Array size: {array_size},
Array dimensions: {array_dimensions},
Array data type: {array_data_type}''')

Object type: <class 'numpy.ndarray'>,
Array size: 5,
Array dimensions: 1,
Array data type: int32


## Similar to lists

In [19]:
ls = [x ** 2 for x in range(10)]
ar = np.arange(10) ** 2
print(ls, ar)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81] [ 0  1  4  9 16 25 36 49 64 81]


In [20]:
print(ls[0], ar[0])

0 0


In [22]:
print(ls[:3], ar[:3])

[0, 1, 4] [0 1 4]


## Differences from lists

In [24]:
ls = [1,2,3,4,5]
print(ls)
print(ls + ls)
print(ls * 2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [25]:
ar = np.arange(1,6,1)
print(ar)
print(ar + ar)
print(ar * 2)

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [29]:
ar1 = np.arange(1,6,1)
s = 2
ls = [2,2,2,2,2]
ar2 = np.array([2,2,2,2,2])

print(ar1 * s)
print(ar1 * ls)
print(ar1 * ar2)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [31]:
ar = np.arange(1,6,1)
print(ar + 2)
print(ar - 2)
print(ar / 2)
print(ar ** 2)
print(ar ** 0.5)
print(ar % 2)

[3 4 5 6 7]
[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[1 0 1 0 1]


## Multiplying two ndarrays

In [32]:
ar1 = np.arange(1,10)
ar2 = np.arange(10,1,-1)
print(ar1, ar2, np.multiply(ar1,ar2),end='\n')

[1 2 3 4 5 6 7 8 9] [10  9  8  7  6  5  4  3  2] [10 18 24 28 30 30 28 24 18]


In [34]:
print(ar1.dot(ar2))

210


In [35]:
print(ar1@ar2)

210


## Some examples of universal functions

In [36]:
ar_ints = np.arange(1,6)
ar_floats = np.arange(1,7.5,1.5)

In [38]:
print(np.add(ar_ints, ar_floats))

[ 2.   4.5  7.   9.5 12. ]


In [40]:
print(np.negative(ar_ints))

[-1 -2 -3 -4 -5]


In [41]:
print(np.square(ar_floats))

[ 1.    6.25 16.   30.25 49.  ]


In [42]:
print(np.hypot(ar_ints, ar_floats))

[1.41421356 3.20156212 5.         6.80073525 8.60232527]


In [44]:
print(np.greater(ar_ints, ar_floats))

[False False False False False]


In [45]:
print(np.ceil(ar_floats))

[1. 3. 4. 6. 7.]


## Statistics

In [47]:
ar3 = np.random.randint(0,10,(10))
print(ar3)

[8 3 8 8 6 3 1 6 9 2]


In [49]:
print(ar3.max(), ar3.mean(), ar3.min(), ar3.std(), ar3.sum(), ar3.var())

9 5.4 1 2.7640549922170505 54 7.639999999999999
