# Numpy!

This section is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. Most codes are hidden and you can only see the output.

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [21]:
# your code is here
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [22]:
# your code is here
int_list = [1,4,2,7,34,6,3,56]
np_int = np.array(int_list)
print(np_int)

[ 1  4  2  7 34  6  3 56]


### Task: Create a numpy array of size 6, filled with zeros

In [23]:
# your code is here
zeros = np.zeros(6)
print(zeros)

[0. 0. 0. 0. 0. 0.]


### Task: Create a numpy array of size 6, filled with ones

In [24]:
# your code is here
ones = np.repeat(1,6)
print(ones)

[1 1 1 1 1 1]


### Task: Create a numpy array with values from 0 to 10

In [25]:
# your code is here
one_to_ten = np.arange(0,11,1)
print(one_to_ten)

[ 0  1  2  3  4  5  6  7  8  9 10]


### Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [26]:
# your code is here
zeros_two = np.zeros(6).reshape(2,3)
print(zeros_two)

[[0. 0. 0.]
 [0. 0. 0.]]


### Task: Create a numpy matrix of 3*2 integers, filled with ones

In [27]:
# your code is here
ones_two = np.repeat(1,6).reshape(3,2)
print(ones_two)

[[1 1]
 [1 1]
 [1 1]]


### Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [28]:
# your code is here
rand_int = np.array([np.random.randint(0,10) for x in range(0,6,1)])
rand_int = rand_int.reshape(3,2)
print(rand_int)

[[0 4]
 [6 4]
 [9 8]]


### Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [32]:
# your code is here
rand_float = np.array([np.random.random() for x in range(0,200,1)])
rand_float = rand_float.reshape(2,100)
print(rand_float)

[[0.32525833 0.51377209 0.36987149 0.01598803 0.3098774  0.55887154
  0.73023337 0.03962028 0.17427193 0.28967123 0.38791266 0.71214169
  0.24243634 0.55819309 0.49728261 0.50010243 0.76403634 0.21145983
  0.36697735 0.51970925 0.45711889 0.1150486  0.59805181 0.07782404
  0.07346199 0.29394508 0.38051342 0.0070971  0.35331383 0.56553277
  0.0125382  0.27463729 0.9534878  0.33775327 0.1000892  0.42386329
  0.63775002 0.52951651 0.00732473 0.90220252 0.04637308 0.73502155
  0.09883128 0.86484784 0.90823006 0.74736452 0.0350877  0.14201676
  0.25100949 0.19742966 0.17294139 0.39382917 0.92268858 0.57637339
  0.53479103 0.62805701 0.13549348 0.6651631  0.0450988  0.65627774
  0.05782152 0.01431516 0.12979848 0.20269638 0.56784877 0.44286106
  0.65419294 0.71114096 0.33867138 0.34859142 0.77225946 0.50848531
  0.28431629 0.34631845 0.63893142 0.36225098 0.72441168 0.22186342
  0.91200027 0.67509379 0.40003038 0.23888325 0.82151839 0.38912129
  0.55558497 0.58993041 0.12826108 0.03361292 0.

### Task: Create a numpy matrix of 2\*3\*4, filled with integers from 1 to 24.

In [36]:
# your code is here
matrix = np.arange(1,25).reshape(2,3,4)
print(matrix)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [37]:
# your code is here
X = np.array([1,2,3,4,5])

### Task: Show the first element of X

In [38]:
# your code is here
print(X[0])

1


### Task: Show the last element of X

In [39]:
# your code is here
print(X[-1])

5


### Task: Show the first 3 elements of X

In [40]:
# your code is here
print(X[:3])

[1 2 3]


### Task: Show the last 3 elements of X

In [42]:
# your code is here
print(X[-3:])

[3 4 5]


### Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [43]:
# your code is here
print(X[0::2])

[1 3 5]


### Task: Show the elements of X except the last one

In [44]:
# your code is here
print(X[:-1])

[1 2 3 4]


### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [47]:
# your code is here
X = np.arange(0,12).reshape(3,4)
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Task: Show the first row of X

In [49]:
# your code is here
print(X[0])

[0 1 2 3]


### Task: Show the first column of X

In [50]:
# your code is here
print(X[:,0])

[0 4 8]


### Task: Show the first element of the first row of X

In [51]:
# your code is here
print(X[0][0])

0


### Task: Show the last row of X

In [52]:
# your code is here
print(X[-1])

[ 8  9 10 11]


### Task: Show the last column of X

In [53]:
# your code is here
print(X[:,-1])

[ 3  7 11]


### Task: Show the last element of the last row of X

In [54]:
# your code is here
print(X[-1,-1])

11


### Task: Show all the rows except the last row of X

In [55]:
# your code is here
print(X[:-1])

[[0 1 2 3]
 [4 5 6 7]]


### Task: Show all the columns except the last column of X

In [57]:
# your code is here
print(X[:,:-1])

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


### Task: Show the first two elements of the first two rows

In [59]:
# your code is here
print(X[:-1,:-2])

[[0 1]
 [4 5]]


## Array Statistics

### Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [67]:
# your code is here
X = np.arange(26,37)
print(X.sum())
print(X.mean())
print(X.std())
print(X.var())
print(X.min())
print(X.max())

341
31.0
3.1622776601683795
10.0
26
36


### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [72]:
# your code is here
X = np.arange(26,38).reshape(3,4)
first_row = X[1]
print(first_row.sum())
print(first_row.mean())
print(first_row.std())
print(first_row.var())
print(first_row.min())
print(first_row.max())

126
31.5
1.118033988749895
1.25
30
33


### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [74]:
# your code is here
X = np.arange(26,38).reshape(3,4)
first_col = X[:,1]
print(first_col.sum())
print(first_col.mean())
print(first_col.std())
print(first_col.var())
print(first_col.min())
print(first_col.max())

93
31.0
3.265986323710904
10.666666666666666
27
35


## Array Linear Algebra

### Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc.

In [83]:
# your code is here
X = np.arange(1,5).reshape(2,2)
Y = np.arange(1,5).reshape(2,2)
print(X+Y)
print(X-Y)
print(X*Y)
print(X.T)
print(X@Y)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[1 3]
 [2 4]]
[[ 7 10]
 [15 22]]
