## Using boolean arrays

In [2]:
import numpy as np

In [3]:
np.random.seed(1)
ar = np.random.randint(100,size=10)
print(ar)

[37 12 72  9 75  5 79 64 16  1]


In [4]:
odd_mask = ar % 2 == 1
print(odd_mask)

[ True False False  True  True  True  True False False  True]


In [6]:
print(ar[odd_mask])

[37  9 75  5 79  1]


In [7]:
ar = np.random.randint(100, size=(10,10))
print(ar)

[[76 71  6 25 50 20 18 84 11 28]
 [29 14 50 68 87 87 94 96 86 13]
 [ 9  7 63 61 22 57  1  0 60 81]
 [ 8 88 13 47 72 30 71  3 70 21]
 [49 57  3 68 24 43 76 26 52 80]
 [41 82 15 64 68 25 98 87  7 26]
 [25 22  9 67 23 27 37 57 83 38]
 [ 8 32 34 10 23 15 87 25 71 92]
 [74 62 46 32 88 23 55 65 77  3]
 [ 0 77  6 52 85 70  2 76 91 21]]


In [8]:
print(ar[ar % 2 == 0])

[76  6 50 20 18 84 28 14 50 68 94 96 86 22  0 60  8 88 72 30 70 68 24 76
 26 52 80 82 64 68 98 26 22 38  8 32 34 10 92 74 62 46 32 88  0  6 52 70
  2 76]


In [9]:
print(ar[ar < 50])

[ 6 25 20 18 11 28 29 14 13  9  7 22  1  0  8 13 47 30  3 21 49  3 24 43
 26 41 15 25  7 26 25 22  9 23 27 37 38  8 32 34 10 23 15 25 46 32 23  3
  0  6  2 21]


In [12]:
ar2 = np.random.randint(100, size = (10,10))
print(ar2)

[[75  7 77 72 75 76 43 20 30 36]
 [ 7 45 68 57 82 96 13 10 23 81]
 [ 7 24 74 92 20 32 12 65 94 60]
 [24 82 97  2 92 98 10 54 96 82]
 [86 70 66 71 48 54 15  5 17 42]
 [20 48 22 13 97 53 84 10 96 55]
 [61 56 89 21 96 83 25 14 13 84]
 [43  6 77 56 59 15 24  9 66 71]
 [53 69 36 21 40 77 91 49 47 77]
 [40 78 45 87 16 28 45 67 66 78]]


In [13]:
print(ar[ar < ar2])

[ 6 25 50 20 18 11 28 14 50 87 13  7 63 61  1  0 60  8 13 72 30  3 70 21
 49 57  3 68 24 43 15 68 25  7 26 25 22  9 23 27 38  8 34 10 23 62 23 55
  3  0 77  6 52  2 21]


In [14]:
print(ar[ar + ar2 > 100])

[76 50 84 50 68 87 87 94 96 86 63 61 60 81 88 13 72 30 70 21 49 57 68 80
 82 68 98  7 23 27 38 34 87 71 92 74 62 88 55 65 77 77 52 85 76 91]
