# Numpy!

This section is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. Most codes are hidden and you can only see the output.

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [ ]:
import numpy as np

## Array Creation

### Task: Create a numpy array from a list of integers

In [ ]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

### Task: Create a numpy array of size 6, filled with zeros

In [ ]:
x = np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

### Task: Create a numpy array of size 6, filled with ones

In [ ]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

### Task: Create a numpy array with values from 0 to 10

In [ ]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [ ]:
X = np.zeros((2, 3))
X

array([[0., 0., 0.],
       [0., 0., 0.]])

### Task: Create a numpy matrix of 3*2 integers, filled with ones

In [ ]:
X = np.ones((3, 2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [ ]:
X = np.random.randint(0, 10, (3, 2))
X

array([[9, 3],
       [9, 8],
       [8, 2]])

### Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [ ]:
X = np.random.random((100, 2))
X

array([[0.86993325, 0.50804537],
       [0.42063141, 0.6547371 ],
       [0.91080167, 0.76571313],
       [0.14421514, 0.87630482],
       [0.79689773, 0.37132623],
       [0.22367667, 0.25620628],
       [0.26828924, 0.864981  ],
       [0.44090925, 0.45742673],
       [0.79426412, 0.78505407],
       [0.31754846, 0.0039239 ],
       [0.55931054, 0.36177125],
       [0.93447121, 0.49561493],
       [0.6201546 , 0.44076041],
       [0.4212216 , 0.61158727],
       [0.30128533, 0.32032619],
       [0.70988004, 0.12327019],
       [0.98866192, 0.03074422],
       [0.21173911, 0.2732957 ],
       [0.89852586, 0.02342201],
       [0.52150973, 0.57959506],
       [0.06279927, 0.00249743],
       [0.67876758, 0.89237965],
       [0.8615494 , 0.51298976],
       [0.71315969, 0.88377509],
       [0.45459553, 0.81958311],
       [0.88257519, 0.06860784],
       [0.30367137, 0.24203548],
       [0.68389771, 0.29885327],
       [0.41343673, 0.85597743],
       [0.41551043, 0.56397876],
       [0.

### Task: Create a numpy matrix of 2\*3\*4, filled with integers from 1 to 24.

In [ ]:
X = np.arange(1, 25).reshape(2, 3, 4)
X

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [ ]:
X = np.array([1, 2, 3, 4, 5])

### Task: Show the first element of X

In [ ]:
X[0]

1

### Task: Show the last element of X

In [ ]:
X[-1]

5

### Task: Show the first 3 elements of X

In [ ]:
X[:3]

array([1, 2, 3])

### Task: Show the last 3 elements of X

In [ ]:
X[2:]

array([3, 4, 5])

### Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [ ]:
X[1::2]

array([2, 4])

### Task: Show the elements of X except the last one

In [ ]:
X[:-1]

array([1, 2, 3, 4])

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [ ]:
X = np.arange(12).reshape(3, 4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Task: Show the first row of X

In [ ]:
X[0]

array([0, 1, 2, 3])

### Task: Show the first column of X

In [ ]:
X[:,0]

array([0, 4, 8])

### Task: Show the first element of the first row of X

In [ ]:
X[0,0]

0

### Task: Show the last row of X

In [ ]:
X[-1]

array([ 8,  9, 10, 11])

### Task: Show the last column of X

In [ ]:
X[:,-1]

array([ 3,  7, 11])

### Task: Show the last element of the last row of X

In [ ]:
X[-1,-1]

11

### Task: Show all the rows except the last row of X

In [ ]:
X[:-1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Task: Show all the columns except the last column of X

In [ ]:
X[:,:-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

### Task: Show the first two elements of the first two rows

In [ ]:
X[:2,:2]

array([[0, 1],
       [4, 5]])

## Array Statistics

### Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [ ]:
print(X.sum(),X.mean(), X.std(), X.var(), X.max(), X.min())

66 5.5 3.452052529534663 11.916666666666666 11 0


### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [ ]:
r1 = X[0]
print(r1.sum(),r1.mean(), r1.std(), r1.var(), r1.max(), r1.min())

6 1.5 1.118033988749895 1.25 3 0


### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [ ]:
c1 = X[:,0]
print(c1.sum(),c1.mean(), c1.std(), c1.var(), c1.max(), c1.min())

12 4.0 3.265986323710904 10.666666666666666 8 0


## Array Linear Algebra

### Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc. 

In [ ]:
X = np.array([[0, 1], [2, 3]])
Y = np.array([[4, 5], [6, 7]])
plus = X + Y
minus = X - Y
times = X * Y
trans = X.T
prod = X @ Y
print(X)
print(Y)
print(plus)
print(minus)
print(times)
print(trans)
print(prod)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 4  6]
 [ 8 10]]
[[-4 -4]
 [-4 -4]]
[[ 0  5]
 [12 21]]
[[0 2]
 [1 3]]
[[ 6  7]
 [26 31]]
